### ISSUE TITLE
How to run this project.

### ISSUE THREAD

**Issue by C-SJK** [sunnyHelen/JPerceiver#2]
Can you provide more details about how to run yours project.

**Comment by sunnyHelen** [comment]
1. Prepare the corresponding dataset

2. Run training

# Training
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=8 --master_port 25629  train.py --config config/cfg_kitti_baseline_odometry_boundary_ce_iou_1024_20.py --work_dir log/odometry/

3. Choose different config files and log directories for different datasets and training settings.

4. The evaluation of BEV layout is conducted during training, which can be found in respective "xxx.log.json" files.

What else information do you need?

**Comment by C-SJK** [comment]
Sorry，I didn`t describe clearly. 
1、I want to run you inference.
2、(argo_both.pth depth_eigen.pth kitti_object.pth kitti_odometry_road.pth kitti_raw_road.pth) this model i don`t know how to use it. So many eval files and which can use to get BEV result.  Can you provide more details about steps
3、I  just get a blue block in BEV seg image  when i use the argo_both.pth and eval_argo_both_video.py inference one image. If i want get the result in your readme show what should i do.

thank you very much!

**Comment by C-SJK** [comment]
Sorry，I didnt describe clearly. 

1. I want to run you inference. 
2. (argo_both.pth depth_eigen.pth kitti_object.pth kitti_odometry_road.pth kitti_raw_road.pth) this model i dont know how to use it. So many eval files and which can use to get BEV result. Can you provide more details about steps.
3.  I just get a blue block in BEV seg image when i use the argo_both.pth and eval_argo_both_video.py inference one image. If i want get the result in your readme show what should i do.

thank you very much!

**Comment by sunnyHelen** [comment]
Hi, if you want to get the BEV layout of images from the Argoverse dataset, you just need to run python scripts/eval_argo_both_video.py.
You need to set the cfg_path, model_path,  img_path and output_path here, according to what dataset do you use and what result you want.
https://github.com/sunnyHelen/JPerceiver/blob/8c8166cae55484a9a5742d42a5fb139e4bc53218/scripts/eval_argo_both_video.py#L346
The cfg_path for both static and object is config/cfg_kitti_baseline_argo_both_boundary_ce_iou_1024_20_B1.py or if you want separate static or object, you can pick the corresponding one in the config files.
The model_path is the path of the downloaded models, i.e., argo_both.pth.
The img_path is a directory containing the image sequences if you want to generate a video.
