### ISSUE TITLE
failed to download ground truth of KITTI from monolayout

### ISSUE THREAD

**Issue by xjixzz** [sunnyHelen/JPerceiver#3]
Hi, thank you for your wonderful work！
I tried to download GT layout of KITTI using the links in monolayout, only to get "404 FILE NOT FOUND".
Can you provide accessible links or other suggestions?

**Comment by sunnyHelen** [comment]
Can this be solved by generating the labels using their script generate_supervision.py?

**Comment by xjixzz** [comment]
Thank you for your reply. I only generated the dynamic layouts for KITTI 3D Object using their script generate_supervision.py. But for KITTI RAW and KITTI Odometry datasets, it seems that only weak static layouts can be generated using the script. The groundtruth static layouts for KITTI RAW and KITTI Odometry datasets are manually annotated. Can they be generated using their script? or I missed something?

**Comment by sunnyHelen** [comment]
Oh, yes. The manually annotated data was downloaded from a link. But their original link is invalid now. Did you contact them? My data is stored in the HPC. I need some time to download and maybe I can upload it.

**Comment by xjixzz** [comment]
I described this problem in the issues of thier repository but still got no response. It would be very helpful if you can upload it. Thanks!

**Comment by xjixzz** [comment]
Thank you so much! I have commited the issue in AutoLay project.

**Comment by sunnyHelen** [comment]
Hi, I downloaded the road label from the hpc. Here are the links. [Kitti Raw](https://drive.google.com/file/d/1CN_-WKsEZrUkdLPv-MFD16PHLlOYHhaJ/view?usp=sharing) and [Kitti Odometry ](https://drive.google.com/file/d/1Z-zqMKiMqlws4s54mEjbKwK9vB_eZ1wE/view?usp=sharing)

**Comment by xjixzz** [comment]
Great, thank you!
