### ISSUE TITLE
ModuleNotFoundError: No module named 'mono.model.mono_autoencoder'

### ISSUE THREAD

**Issue by xjixzz** [sunnyHelen/JPerceiver#4]
https://github.com/sunnyHelen/JPerceiver/blob/802e511b8a32e798bcc69df40f82dddbe12d97d4/mono/model/__init__.py#L2-L4
Hi, the mono_autoencoder folder is missing.

**Comment by sunnyHelen** [comment]
Hi, thanks for your reminder. We don't need the autoencoder, mono_fm and mono_fm_joint. Just delete it.
