### ISSUE TITLE
inputs['bothD', 0, 0] missed in training process

### ISSUE THREAD

**Issue by RikkyLai** [sunnyHelen/JPerceiver#6]
After the datasets needed are downloaded, I ran the commanding code
`# Training
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=8 --master_port 25629  train.py --config config/cfg_kitti_baseline_odometry_boundary_ce_iou_1024_20.py --work_dir log/odometry/
`
However, `KeyError: ('bothD', 0, 0)` happened when computing the _loss_dict_  of _odometry_ dataset.. 
I noticed that when computing the loss of _kitti_object_, `inputs['bothD', 0, 0]` could be provided by getting groundtruth _vehicle256_, while  `inputs[''bothS, 0, 0]` could be provided by getting groundtruth _road dense128_ . 
Since the topview_lossB requires `inputs['bothD', 0, 0]` when I run _odometry_ dataset, how can I get this variable?
How about running _kitti object_ dataset, where can I find `inputs['bothS', 0, 0]` ?
Thanks.

**Comment by sunnyHelen** [comment]
For kitti_odometry and kitti_raw split, the default setting is just using inputs['bothS', 0, 0] and just predicting the road layout. If you need inputs['bothD', 0, 0] for these two splits, you can generate them using the trained object layout network.

**Comment by RikkyLai** [comment]
So the  (since they need inputs['bothD', 0, 0] to compute loss top view B)
https://github.com/sunnyHelen/JPerceiver/blob/22ea4c8d2350b54c1b0c45b45466404acc556fd0/net.py#L152
https://github.com/sunnyHelen/JPerceiver/blob/22ea4c8d2350b54c1b0c45b45466404acc556fd0/net.py#L156
could be commented for _kitti_odometry_ split and _kitti_raw_ ?

**Comment by sunnyHelen** [comment]
Yes, I've changed the net.py by adding an if-else judgment.

**Comment by RikkyLai** [comment]
Thanks!
